import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class LanguageService {
  constructor() {}

  languages_1 = {
    english: {},
    arabic: {
      saturday: "السبت",
      sunday: "الأحد",
      monday: "الاثنين",
      tuesday: "الثلاثاء",
      wednesday: "الأربعاء",
      thursday: "الخميس",
      friday: "الجمعة",



      "the doctor was successfully added":"تمت إضافة الطبيب بنجاح",
      "the doctor was successfully updated":"تم تعديل الطبيب بنجاح",
      "the correspondent was successfully added":"تمت إضافة الجهة بنجاح",
      "the correspondent was successfully updated":"تم تعديل الجهة بنجاح",
      "the patient was successfully added":"تمت إضافة المريض بنجاح",
      "the patient was successfully updated":"تم تعديل المريض بنجاح",
      "the request was successfully created":"تمت إنشاء الطلب بنجاح",
      "the request was successfully updated":"تم تعديل الطلب بنجاح",
      "the payment was successfully made":"تم الدفع بنجاح",
      "the discount was successfully added":"تم إضافة التخفيض بنجاح",
      logout:"تسجيل الخروج",
      "select a category": "إختر فئة",
      "current password": "كلمة المرور القديمة",
      "new password": "كلمة المرور الجديدة",
      "confirm password": "تأكيد كلمة المرور",
      results: "النتائج",
      "print results":"طباعة النتائج",
      "with categories?":"مع الفئات؟",
      "with devices?":"مع الأجهزة؟",
      "select tests to print":"إختر تحاليل للطباعة",
      'patient or | and correspondent':"مريض و | أو جهة",
      home: "الصفحة الرئيسية",
      search: "البحث",
      patients: "المرضى",
      requests: "الطلبات",
      request: "الطلب",
      nationality: "الجنسية",
      draw: "سحب",
      "delete reason": "سبب الحذف",
      reason: "السبب",
      "request #": "رقم الطلب",
      "patient name": "اسم المريض",
      "patient id": "الرمز الشخصي المريض",
      "doctor name": "اسم الطبيب",
      "result state": "حالة النتيجة",
      area: "المجال",
      // 'result expression':'',
      "date from": "التاريخ من",
      "date to": "التاريخ إلى",
      "time from": "الوقت من",
      "time to": "الوقت إلى",
      paid: "مدفوع",
      unpaid: "غير مدفوع",
      add: "إضافة",
      close:"إغلاق",
      "draw sample": "سحب عينة",
      "Draw Time": "موعد السحب",
      download:'تحميل',
      "with result": "مع نتيجة",
      "without result": "بدون نتيجة",
      "hospital id": "رقم المريض في المستشفى",
      "search by request #": "البحث برقم الطلب",
      "search by request code": "البحث برمز الطلب",
      "search by patient name": "البحث باسم المريض",
      "search by doctor name": "البحث باسم الطبيب",
      "patients list": "قائمة المرضى",
      "search by patient name or phone or birthdate or barcode":
        "البحث بالاسم أو رقم الهاتف أو تاريخ الميلاد أو الباركود",

        "search by patient name, id or phone number or national id":
        "البحث باسم أو الرمز الشخصي أو رقم الهاتف للمريض أو الرقم الوطني",

      "search by patient name or hospital id or phone or birthdate or barcode":
        "البحث بالاسم أو رقم المستشفى أو رقم الهاتف أو تاريخ الميلاد أو الباركود",



        "search by patient name or hospital id or phone or birthdate or barcode or national id":
        "البحث بالاسم أو رقم المستشفى أو رقم الهاتف أو تاريخ الميلاد أو الباركود أو الرقم الوطني",

      login:'تسجيل الدخول',

      "please pick at least one test | profile":"الرجاء إختيار تحليل | ملف تحاليل واحد على الأقل",

      action: "النشاط",
      activity: "الفعالية",
      edit: "تعديل",
      "activity log": "سجل النشاطات",
      parameter: "الباراميتر",
      "patient info": "بيانات المريض",
      "request info": "بيانات الطلب",
      "search by code": "ابحث بالرمز",
      change: "تغيير",
      arabic: "العربية",
      english: "الإنجليزية",
      "change your credentials": "تعديل البيانات الشخصية",
      "change language": "تغيير اللغة",
      "tests | profiles": "التحاليل | ملفات التحاليل",
      "add tests | profiles": "أضف التحاليل | ملفات التحاليل",
      "search by test | profile code": "البحث برمز التحليل | ملف التحاليل",
      "search by test | profile code or name": "البحث برمز أو اسم التحليل | ملف التحاليل",
      "test | profile": "التحليل | ملف التحاليل",
      test: "التحليل",
      tests: "التحاليل",
      correspondents: "الجهات",
      "correspondents list": "قائمة الجهات",
      "all correspondents": "جميع الجهات",
      all: "الكل",
      print: "طباعة",
      previous: "السابق",
      next: "التالي",
      category: "الفئة",
      parameters: "العوامل",
      doctors: "الأطباء",
      doctor: "الطبيب",
      pricing: "التسعير",
      reports: "التقارير",
      language: "اللغة",
      civility:"الوصف",
      excel:"اكسل",
      "info bill":"فاتورة تفصيلية",
      "info bill separate pages":"فاتورة تفصيلية صفحات منفصلة",
      'payment status' : 'حالة الدفع',
      "total rows": "عدد الصفوف",
      "in | out patient": "إيواء | عيادة خارجية",
      "in patient": "إيواء",
      "out patient": "عيادة خارجية",
      // "charge to":"",
      "clinical information": "المعلومات الطبية",
      "payment information": "معلومات الدفع",
      "laboratory information": "المعلومات المختبرية",
      "laboratory notes": "الملاحظات المختبرية",
      "hospitalization date": "تاريخ الإدخال",
      username: "اسم المستخدم",
      password: "كلمة المرور",
      new: "جديد",
      normal: "عادي",
      urgent: "مستعجل",
      none: "لا يوجد",
      patient: "المريض",
      correspondent: "الجهة",
      "correspondent id": "رقم المريض في الجهة",
      balance: "الرصيد",
      "patient card": "بطاقة المريض",
      "total price calculation":"حساب إجمالي السعر",
      id: "الرمز الشخصي",
      date: "التاريخ",
      result: "النتيجة",
      status: "الحالة",
      payments: "المدفوعات",
      "request payment": "دفع الطلب",
      "request discount": "تخفيض الطلب",
      "request summary": "ملخص الطلب",
      pay: "ادفع",
      "payment methods": "طرق الدفع",
      "payment method": "طريقة الدفع",
      "charged to clinic":"على حساب العيادة",
      clinic:"العيادة",
      "this request is charged to clinic":"هذا الطلب على حساب العيادة",
      "the request has been set to delivered":"تم تغيير حالة الطلب إلى تم التسليم",
      "please enter all data correctly and try again":"الرجاء إدخال جميع البيانات بطريقة صحيحة",
      "please enter either age or birthdate":"الرجاء إدخال العمر أو تاريخ الميلاد",
      "payment date": "تاريخ الدفع",
      amount: "القيمة",
      payer: "الدافع",
      cashier: "الخزينة",
      total: "الإجمالي",
      remaining: "المتبقي",
      "total charged": "الإجمالي النهائي",
      summary: "الملخص",
      urgency: "الاستعجالية",
      repeat: "إعادة",
      delivered: "تم التسليم",
      ready: "جاهز",
      active: "نشط",
      "in progress": "قيد التجهيز",
      save: "حفظ",
      code: "الرمز",
      profile: "ملف تحاليل",
      original: "السعر الأصلي",
      discount: "التخفيض",
      "set discount": "إضافة تخفيض",
      "discount percentage": "نسبة التخفيض",
      percentage: "النسبة المئوية",
      percent: "النسبة المئوية",
      value: "القيمة",
      "discount value": "قيمة التخفيض",
      "national id": "الرقم الوطني",
      transactions: "المعاملات",
      charged: "السعر النهائي",
      remove: "إزالة",
      name: "الاسم",
      receptionist: "موظف إستقبال",
      technician: " فني ",
      accountant: " محاسب ",
      "charge to":"على حساب",
      admin: " مسؤول ",
      notes: 'الملاحظات',
      "the note was successfully updated": "تم تعديل الملاحظة بنجاح",
      history:'السجل',
      "sorry you can't update validated request":"عذرََا, لا يمكن تعديل طلب متحقق من صحته",
      phone: "رقم الهاتف",
      "phone number": "رقم الهاتف",
      specify: "تحديد",
      barcode: "الباركود",
      birthdate: "تاريخ الميلاد",
      "patient search": "البحث ببيانات المريض",
      "this field is required": "هذا الحقل مطلوب",

      "please pick a firstname for the patient":"الرجاء إضافة اسم أول للمريض",
      "please pick a lastname for the patient":"الرجاء إضافة لقب للمريض",
      "please pick birthdate or age for the patient":"الرجاء إضافة تاريخ ميلاد أو عمر للمريض ",

      "change password":"تغيير كلمة المرور",
      "first name": "الاسم الأول",
      "middle name": "اسم الأب",
      "last name": "اللقب",
      years: "سنوات",
      months: "شهور",
      days: "أيام",
      gender: "الجنس",
      "select a date": "إختر تاريخ",
      "select a patient": "إختر مريض",
      "lab":"المعمل",
      age: "العمر",
      "new patient": "مريض جديد",
      "new doctor": "طبيب جديد",
      "edit patient": "تعديل بيانات مريض",
      "edit request": "تعديل بيانات الطلب",
      "new request": "طلب جديد",
      "edit doctor": "تعديل بيانات طبيب",
      male: "ذكر",
      female: "أنثى",
      "doctor list": "قائمة الأطباء",
      specialty: "التخصص",
      delete: "حذف",
      "are you sure you want to remove this doctor?":
        "هل أنت متأكد من حذف هذا الطبيب؟",
      yes: " نعم ",
      no: " لا ",
      type: "النوع",

      "detailed invoice": "فاتورة مفصلة",
      "print receipt": "طباعة الإيصال",
      "print barcodes": "طباعة الباركودات",
      "single sticker": "ملصق واحد",

      calculate:"احسب",
      cancel:"رجوع",
      "draw time":"وقت السحب",
    },
  };

  languages_2 = {
    english: {},
    arabic: {
      repeat: "معاد",
      percentage: "نسبة مئوية",
      percent: "نسبة مئوية",
      value: "قيمة",
      test: "تحليل",
      profile: "ملف تحاليل",
      package: "حزمة",
      id: "ر.م",
      receptionist: " الإستقبال ",
      technician: " المختبر ",
      accountant: " المالية ",
      admin: " الإدارة ",

    },
  };
}
